env_id: 'BreakoutNoFrameskip-v4'
method: 'action'
config_path: 'min_red/config'
algorithm_type: 'PPO'
total_timesteps: 5000000
env_kwargs: 'empty_dict'
n_envs: 10
vis: False
wrapper_kwargs:
  macro_length: 1
  wandb_log_interval: 10000
vec_env_kwargs: 'empty_dict'
is_atari: True
play_model: False
save_model: False
