env_id: 'BreakoutNoFrameskip-v4'
method: 'action'
config_path: 'min_red/config'
algorithm_type: 'PPO'
total_timesteps: 5000000
env_kwargs: 'empty_dict'
vec_env_kwargs: 'empty_dict'
is_atari: True
play_model: False
save_model: False
wandb: False
