discrete: True
off_policy: True

policy:
  learning_rate: 0.0001
  gamma: 0.99  # 0.9
  buffer_size: 1000000  # 50000
  learning_starts: 50000
  regularization_starts: 150000
  batch_size: 32
  exploration_initial_eps: 1.
  exploration_final_eps: 0.05
  target_update_interval: 10000  # 1000
  tau: 1
  policy_kwargs: 'empty_dict'
  verbose: 1
  method: None
  threshold: None

learn:
  total_timesteps: None
  log_interval: 10


