env_id: 'Hopper-v2'
method: 'action'
algorithm_type: 'SAC'
config_path: 'min_red/config'
ensemble_size: 1
total_timesteps: 100000
step_mixture: True
env_kwargs: 'empty_dict'
vec_env_kwargs: 'empty_dict'
wrapper_kwargs:
  macro_length: 1
  wandb_log_interval: 1000
is_atari: False
play_model: False
save_model: False
video_config:
  length: 100
  interval: 10000