env_id: 'rooms-v0'
method: 'action'
config_path: 'min_red/config'
algorithm_type: None  # SoftQ, PPO
total_timesteps: 100000
env_kwargs:
  rows: 10
  cols: 10
  empty: False
  goal: [1, 1]
  state: [8, 8]
  fixed_reset: True
  vert_wind: [0.0, 0.0] # (up, down)
  horz_wind: [0.0, 0.0] # (right, left)
  n_redundancies: 1
  max_repeats: 3
  vis: False
n_envs: 2
vec_env_kwargs: 'empty_dict'
is_atari: False
play_model: False
save_model: False
wandb: False
