env_id: 'rooms-v0'
method: 'action'
config_path: 'min_red/config'
algorithm_type: None  # SoftQ, PPO, GroupedQ
discrete: False
total_timesteps: 100000
env_kwargs:
  rows: 16
  cols: 16
  empty: False
  goal: [1, 1]
  state: [14, 14]
  fixed_reset: True
  vert_wind: [0.0, 0.0] # (up, down)
  horz_wind: [0.0, 0.0] # (right, left)
  n_redundancies: 1
  max_repeats: 3
n_envs: 1
wrapper_kwargs:
  macro_length: 1
  vis: False
  wandb_log_interval: 1000
vec_env_kwargs: 'empty_dict'
is_atari: False
play_model: False
save_model: False
video_config:
  length: 100
  interval: 0