env_id: 'rooms-v0'
method: 'deterministic'
config_path: 'min_red/config'
algorithm_type: 'SoftQ'
total_timesteps: 100000
env_kwargs:
  rows: 10
  cols: 10
  empty: False
  goal: [1, 1]
  state: [8, 8]
  fixed_reset: True
  vert_wind: [0.0, 0.0] # (up, down)
  horz_wind: [0.0, 0.0] # (right, left)
  n_redundancies: 20
  max_repeats: 3
vec_env_kwargs: 'empty_dict'
is_atari: False
play_model: False
save_model: False
wandb: False
