discrete: False
off_policy: True

policy:
  learning_rate: 0.0003
  gamma: 0.99
  buffer_size: 50000
  learning_starts: 10000
  batch_size: 256
  target_update_interval: 1
  policy_kwargs: 'empty_dict'
  verbose: 1
  train_freq: 1000
  gradient_steps: 1000
  method: None
  ent_coef: 'auto'
  importance_sampling: True

buffer:
  prioritized_ensemble: False

learn:
  total_timesteps: None
  log_interval: 1


