env_id: 'Hopper-v2'
method: 'entropy'
algorithm_type: 'SAC'
ensemble_size: 1
total_timesteps: 100000
step_mixture: True
env_kwargs: 'empty_dict'
vec_env_kwargs: 'empty_dict'
is_atari: False
play_model: False
save_model: False
wandb: False