discrete: False

policy:
  learning_rate: 0.0003
  gamma: 0.99
  buffer_size: 300000
  learning_starts: 10000
  batch_size: 256
  target_update_interval: 1
  policy_kwargs: 'empty_dict'
  verbose: 1
  net_arch: [300, 400]
  train_freq: 1000
  gradient_steps: 1000
  noise_type: 'none'
  noise_std: 0.1
  shared_critic: False
  method: None
  ent_coef: 'auto'

buffer:
  prioritized_ensemble: False

learn:
  total_timesteps: None
  log_interval: 1


